pip_audit/service/__init__.py, pip_audit/service/interface.py, pip_audit/service/service.py, setup.py, test/conftest.py, test/service/test_interface.py
=> service: add `VulnerabilityService` interface type

pip_audit/format/__init__.py, pip_audit/format/columns.py, pip_audit/format/interface.py, pip_audit/format/json.py, pip_audit/service/__init__.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_json.py, test/format/vuln_data.py
=> Add columns and JSON output formats

pip_audit/dependency_source/__init__.py, pip_audit/dependency_source/interface.py, pip_audit/dependency_source/pip.py, pip_audit/service/interface.py, setup.py, test/conftest.py, test/dependency_source/test_interface.py, test/dependency_source/test_pip.py
=> pip_audit: dependency source skeleton

mypy.ini
This adds some reasonable MyPy defaults to ratchet down our typing a bit more.
=> mypy: add config

pip_audit/dependency_source/pip.py, setup.py
=> setup, pip_audit: bump pip-api, enable MyPy for import

pip_audit/audit.py, pip_audit/cli.py, pip_audit/format/__init__.py, pip_audit/service/interface.py, pip_audit/util.py, test/test_audit.py
=> Auditor skeleton

.bump, .github/workflows/release.yml, Makefile, README.md, setup.py
Adds an appropriate classifier, and a release workflow.
=> RC release prep

pip_audit/audit.py, pip_audit/service/interface.py, test/service/test_interface.py, test/service/test_osv.py, test/test_audit.py
Per https://github.com/trailofbits/pip-audit/issues/28#issuecomment-920943310.
=> pip_audit, test: make interfaces lazier

pip_audit/format/columns.py, pip_audit/format/json.py, pip_audit/service/__init__.py, pip_audit/service/interface.py, pip_audit/service/osv.py, test/conftest.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_json.py, test/test_audit.py
=> Use OSV 1.0 format

pip_audit/dependency_source/resolvelib/pypi_wheel_provider.py, test/dependency_source/test_resolvelib.py
=> Add support for extras in `PyPIProvider`

pip_audit/dependency_source/__init__.py, pip_audit/dependency_source/interface.py, pip_audit/dependency_source/resolvelib/__init__.py, pip_audit/dependency_source/resolvelib/pypi_provider.py, pip_audit/dependency_source/resolvelib/pypi_wheel_provider.py, pip_audit/dependency_source/resolvelib/resolvelib.py, setup.py, test/dependency_source/test_resolvelib.py
=> Add support for source distributions in `PyPIProvider`

CONTRIBUTING.md, README.md
Remove from README, replace with installation steps.
Closes #78.
=> CONTRIBUTING, README: add contributing documentation

pip_audit/service/pypi.py
=> service/pypi: fix cache bugs

CONTRIBUTING.md, Makefile
Makes the `make test` target slightly smarter.
=> Makefile, CONTRIBUTING: small testing niceties

pip_audit/dependency_source/resolvelib/pypi_provider.py, pip_audit/virtual_env.py, test/dependency_source/test_resolvelib.py
=> pip_audit: Update state feedback when fetching metadata

README.md, pip_audit/cli.py
=> cli: Add result summary and fix exit codes

pip_audit/cli.py
=> cli: Add option to toggle progress spinner

.github/workflows/ci.yml, Makefile, README.md
=> CI, Makefile, README: enforce `pip-audit --help` changes

README.md, pip_audit/dependency_source/pip.py, pip_audit/dependency_source/requirement.py, pip_audit/format/columns.py, pip_audit/format/json.py, pip_audit/service/interface.py, pip_audit/service/osv.py, pip_audit/service/pypi.py, test/conftest.py, test/dependency_source/test_pip.py, test/dependency_source/test_resolvelib.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_json.py, test/service/test_osv.py
Also adds a positive test for a known vulnerability when passing
an uncanonicalized name.
Fixes #107.
=> pip_audit, test: canonicalize package names for the OSV service

mypy.ini, pip_audit/cli.py, pip_audit/dependency_source/resolvelib/pypi_provider.py
=> pip_audit/cli: enforce mypy, fix errors

CONTRIBUTING.md, Makefile, pip_audit/__init__.py, pip_audit/_version.py, pip_audit/dependency_source/resolvelib/resolvelib.py, setup.py
=> Enable documentation builds, document doc builds

README.md, pip_audit/cli.py, pip_audit/dependency_source/resolvelib/pypi_provider.py, pip_audit/dependency_source/resolvelib/resolvelib.py, pip_audit/service/osv.py, pip_audit/service/pypi.py, test/dependency_source/test_resolvelib.py, test/service/test_pypi.py
=> pip_audit: Add timeout for network requests

pip_audit/_state.py
Fixes #135.
The new behavior is as follows: lines are printed as normal, but with each line we check the current row's column count. If the message is too large to print, then we do one of two things:
1. If the column is wide enough to print a partial message, we do so, reserving some space for a "truncation indicator" (currently just ` ...`).
2. If the column isn't wide enough for our truncation indicator to fit in the partial message, we just perform the truncation. This should almost always be a degenerate case, since `len(" ...") == 4` and terminal widths at or below that are unlikely to render anything correctly anyways.
Example of the new behavior:
[![asciicast](https://asciinema.org/a/450731.svg)](https://asciinema.org/a/450731)
=> pip_audit/_state: truncate progress lines if they wrap

pip_audit/_state.py
=> _state: Buffer logging while spinner is active

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md
Adds a list of development practices, and encourages people to submit their logs with bug reports.
=> CONTRIBUTING, ISSUE_TEMPLATE: add more advice

CHANGELOG.md, CONTRIBUTING.md, README.md, setup.py
This ties off a few loose ends needed for an initial 1.0.0. 
Closes #90.
=> Stabilization!

CHANGELOG.md, README.md, pip_audit/__main__.py
=> Add a module entrypoint

CHANGELOG.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_util.py, test/test_util.py
=> pip_audit, test: make Python runtime version retrieval more resilient

pip_audit/__init__.py, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/resolvelib/__init__.py, pip_audit/_format/__init__.py, pip_audit/_service/__init__.py
=> pip_audit: avoid noqa: F401 using dunder-all

README.md
Sell ourselves a bit!
We do this for most of our other OSS projects, so I figure it doesn't hurt here.
=> README: highlight a few features

CHANGELOG.md, setup.py
=> setup: pip-api >= 0.0.26

README.md
=> README: document third-party packages

Makefile
Makes the rules even more generic.
=> Makefile: use PY_MODULE everywhere

pip_audit/_subprocess.py, pip_audit/_virtual_env.py, test/test_subprocess.py, test/test_virtual_env.py
Closes #227.
Demo:
[![asciicast](https://asciinema.org/a/465724.svg)](https://asciinema.org/a/465724)
=> Make the CLI more responsive

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, setup.py
=> Bump minimum Python to 3.7

CHANGELOG.md
Sorry, forgot to update the changelog in the PR that just went in.
=> CHANGELOG: Add hash checking functionality to changelog

test/conftest.py, test/dependency_source/test_requirement.py, test/dependency_source/test_resolvelib.py, test/service/test_osv.py, test/service/test_pypi.py, test/test_virtual_env.py
=> test: Add `--skip-online` flag to PyTest

setup.py
=> setup: use importlib instead of exec

.pre-commit-config.yaml
Cuz quick automatic feedback is nice 😄
=> ci(pre-commit): add config

pyproject.toml
=> build(setuptools): add requires-python

.bump, Makefile, pip_audit/__init__.py, pip_audit/_version.py, pyproject.toml, setup.py
=> qa: use flit as our build backend

.bump, pyproject.toml
=> pyproject: migrate bump config

README.md
Not sure if this is the best section for it.
=> README: link to the new GitHub Action

.github/dependabot.yml
=> dependabot: check for github actions updates

CHANGELOG.md
=> CHANGELOG: fix link

.pre-commit-config.yaml, README.md
=> README, pre-commit-config: update pip-audit rev

README.md
=> README: bump gh-action-pip-audit version

pyproject.toml
=> pyproject: update authors, classifiers

CHANGELOG.md, CONTRIBUTING.md, README.md, pyproject.toml
=> meta: update trailofbits slugs to pypa

.pre-commit-config.yaml
=> pre-commit: update URL to pypa

README.md
=> README: add a troubleshooting section for false positives

.github/workflows/ci.yml, pyproject.toml
=> workflows/ci: add Python 3.11

CHANGELOG.md
=> CHANGELOG: record #393

CHANGELOG.md, pip_audit/_cli.py
Fixes #398.
cc @norg; thank you again for reporting this!
=> _cli: fix `--desc auto`'s behavior with `--format json`

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
Just to get the recent bugfixes out the door.
=> Release: prep 2.4.6

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
To deliver @woodruffw's work on #417.
=> Release: prep 2.4.7

README.md, pip_audit/_cli.py
cc @CribberSix: let us know if this helps to clarify how the option can be used!
Closes #419.
=> Improve our documentation of `--ignore-vuln`

README.md
=> README: clarify pip-audit behavior around exit codes

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> treewide: prep 2.4.9

CHANGELOG.md
=> CHANGELOG: fix a link typo

test/test_cli.py
Added a unit test to get some extra coverage for #437.
=> test: Add CLI test to check when the formatted result is printed

README.md, pip_audit/_cli.py
This is inspired by the refactor in
https://github.com/sigstore/sigstore-python/pull/372.
=> _cli: refactor logging

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
Let's cut a patch release to get #445 out the door.
=> treewide: prep 2.4.11

CHANGELOG.md
Small mistake on my part!
@tetsuo-cpp mind doing a release PR after this? Alternatively, feel free to take this branch over :slightly_smiling_face:
=> CHANGELOG: fix entry

pip_audit/_cli.py
Add debug log to understand what package has been parsed
Ticket #459
=> add debug log package

pyproject.toml
=> pyproject: constrain ruff

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
Just to get #471 out the door.
=> Prep 2.4.13

Makefile
Uses `VENV` and `VENV_BIN` to make the Makefile more generic, which should help the occasional Windows contributor.
=> Makefile: Windows accommodations

.github/workflows/docs.yml, Makefile, pyproject.toml
=> Refactor docs build, replace pdoc3

CHANGELOG.md, pip_audit/__init__.py
Just to get #477 out the door.
=> prep 2.4.14

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
We merged a few chunky fixes in recently. Let's cut a release and check in with the original reporters.
=> prep 2.4.15

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_dependency_source/pip.py, pip_audit/_dependency_source/requirement.py, pip_audit/_fix.py, pip_audit/_format/cyclonedx.py, test/dependency_source/test_requirement.py
=> CHANGELOG: mark 2.4.15 as yanked

pip_audit/_dependency_source/pyproject.py, pip_audit/_dependency_source/requirement.py
=> requirement: Support process substitution inputs

.github/workflows/release.yml
Now that we've merged this upstream 🙂
=> workflows/release: use OIDC exchange

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> Prep 2.5.1

.github/workflows/release.yml
=> workflows/release: fix indentation

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Only copy FIFO files into temporary files

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> chore: prep 2.5.5

CHANGELOG.md
=> CHANGELOG: fix entries

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
Preps 2.5.6 to get #617 out the door.
=> treewide: 2.5.6

pip_audit/_format/cyclonedx.py
As mentioned in #625 I've simplified the usage of the CycloneDx
=> simplified the usage of CycloneDx

pip_audit/_cache.py, pyproject.toml
...and remove our subdep constraint.
=> pyproject: bump CacheControl

README.md
content is based on the discussion with @woodruffw and @di in #670
closes #670
PS: feel free to improve it as you see fit.
=> add note on ignoring unfixed vulnerabilities

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py, pyproject.toml
=> prep 2.6.2

CHANGELOG.md, pip_audit/_cli.py
=> _cli: remove a misleading warning

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> prep 2.7.0

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> prep 2.7.1

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> prep 2.7.2

README.md
Corrects the troubleshooting docs now that #742 has a known resolution.
=> README: fixup troubleshooting docs based on #742

CHANGELOG.md
=> CHANGELOG: record #756

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/scorecards.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, pip_audit/_audit.py, pip_audit/_cli.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/pip.py, pip_audit/_dependency_source/pyproject.py, pip_audit/_dependency_source/requirement.py, pip_audit/_fix.py, pip_audit/_format/columns.py, pip_audit/_service/interface.py, pip_audit/_state.py, pip_audit/_subprocess.py, pip_audit/_virtual_env.py, pyproject.toml
=> drop 3.8, add 3.13

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/scorecards.yml, .github/workflows/zizmor.yml
Addresses some low findings from `zizmor` + adds a security scanning workflow that'll catch anything else that pops up, proactively.
=> workflows: address zizmor findings, add zizmor workflow

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
=> chore: prep 2.9.0

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/zizmor.yml, Makefile, pyproject.toml
Cleans up the project metadata and Makefile a bit; bumps the `ruff` dev-dep.
Also removes @tetsuo-cpp's old email (@tetsuo-cpp you're still a maintainer, LMK if you want a new email added here!)
=> chore: metadata cleanup

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_service/__init__.py, pip_audit/_service/esms.py, test/service/test_esms.py
=> Implement the Ecosyste.ms vulnerability backend
