pip_audit/cli.py, pip_audit/service/__init__.py, pyproject.toml, test/conftest.py
As-is:
```
usage: pip-audit [-h] [-r REQUIREMENTS] [-f {plain,json}] [-s {osv,pypi}] [-d]
audit the Python environment for dependencies with known vulnerabilities
optional arguments:
-h, --help            show this help message and exit
-r REQUIREMENTS, --requirement REQUIREMENTS
audit the given requirements file; this option can be
used multiple times (default: [])
-f {plain,json}, --format {plain,json}
the format to emit audit results in (default: plain)
-s {osv,pypi}, --vulnerability-service {osv,pypi}
the vulnerability service to audit dependencies
against (default: osv)
-d, --dry-run         collect all dependencies but do not perform the
auditing step (default: False)
```
I'll create individual board items for the functionality under each of these flags.
=> CLI skeleton

setup.py
Subdependencies of a package shouldn't be pinned as it increases the likelihood of an unresolvable dependency set.
=> Remove subdependency pins

pip_audit/audit.py, pip_audit/cli.py, setup.py
Adds a `progress` based progress indicator to the CLI.
Some notes:
* I've subclasses `progress.spinner.Spinner` into `AuditSpinner` to make it behave a little better (the spin icon is on the LHS now, and we show each item being processed to give the user more feedback)
* I've confirmed that the default behavior of `progress` is reasonable when `stdout`/`stderr` aren't TTYs and that it doesn't interfere with our logging or other output
=> Progress indicator

setup.py
Part of stdlib now since 3.7: 
https://docs.python.org/3/library/dataclasses.html
=> Fix setup.py requirements for dataclasses. dataclasses is part of Py3.7+

pip_audit/service/pypi.py, test/service/test_pypi.py
=> service/pypi: Use full cache path instead of directory name

pip_audit/_dependency_source/pip.py, test/dependency_source/test_pip.py
=> _dependency_source/pip: Log a warning and skip auditing for packages with invalid versions

pip_audit/_cli.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/pip.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, pip_audit/_format/columns.py, pip_audit/_format/cyclonedx.py, pip_audit/_format/json.py, pip_audit/_service/__init__.py, pip_audit/_service/interface.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, test/conftest.py, test/dependency_source/test_pip.py, test/dependency_source/test_requirement.py, test/dependency_source/test_resolvelib.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_cyclonedx.py, test/format/test_json.py, test/service/test_interface.py, test/service/test_osv.py, test/service/test_pypi.py
=> pip_audit: Add skipped dependencies to audit summary

README.md, pip_audit/_cli.py, pip_audit/_dependency_source/pip.py, pip_audit/_service/pypi.py, test/dependency_source/test_pip.py, test/service/test_pypi.py
=> README, _cli: Add a `-S`, `--strict` mode

CHANGELOG.md, README.md, pip_audit/_cli.py
The `--desc` option's parameter is optional, and has the following semantics:
* No `--desc` whatsoever: `"auto"`
* Bare `--desc` (no parameter): `"on"`
* `--desc <choice>`: whatever choice is given
See #152.
=> _cli: Fix the behavior of the `--desc` flag

CHANGELOG.md, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/test_resolvelib.py
=> _dependency_source: Return a `SkippedDependency` when the resolver can't find a project on PyPI

CHANGELOG.md, pip_audit/_service/pypi.py
In a scenario where the pip cache directory isn't available because the
user doesn't have permissions; pip will error with this message:
```
ERROR: pip cache commands cannot function since cache is disabled.
```
This currently cannot be mitigated by specifying the `--cache-dir` flag
because the `python -m pip cache dir` command is execute before this
predicate is evaluated. By using an assignment expression (PEP 572), we
can evaluate whether the expression evaluates to a truthy value in the
`elif` branch (saving it's return value) AFTER first evaluating the
custom directory value.
=> _service/pypi.py: Do not execute pip cache command when a custom directory is provided

Makefile, test/dependency_source/test_pip.py, test/dependency_source/test_requirement.py, test/dependency_source/test_resolvelib.py, test/format/conftest.py, test/service/test_osv.py, test/service/test_pypi.py, test/test_audit.py
=> test, Makefile: Run MyPy across unit tests

CHANGELOG.md, pip_audit/_state.py
=> _state: clear the spinner entirely when done

README.md
=> README: document the security model

CHANGELOG.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_util.py, pip_audit/_virtual_env.py
=> Don't explode sdists before installing them

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, README.md, pip_audit/_cli.py
=> _cli: Create --verbose flag

CHANGELOG.md, pip_audit/_service/pypi.py
Closes #169.
@schlenk or @matthewdeanmartin: could you give this a spin and see if it improves the caching situation on your hosts?
=> pypi: add a retry loop for cache updates

pip_audit/_cli.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/test_resolvelib.py
This expands our HTTP caching to include all requests during dependency collection, not just auditing.
Using a very small and contrived input, I see a roughly 10% performance improvement.
Cold starts:
```
real    0m10.721s
user    0m7.593s
sys     0m1.881s
real    0m11.205s
user    0m7.718s
sys     0m1.911s
real    0m11.056s
user    0m7.637s
sys     0m1.889s
```
Versus hot starts:
```
real    0m9.909s
user    0m7.412s
sys     0m1.818s
real    0m10.006s
user    0m7.403s
sys     0m1.827s
real    0m10.248s
user    0m7.491s
sys     0m1.863s
```
Those numbers should be even better for real dependency trees, since we'd expect (1) for users to have a lot cached already, and (2) for medium-to-large projects to have a large number of mutual transitive dependencies.
Closes #187.
=> pip_audit, test: perform even more PyPI caching

README.md, setup.py
~~Clarifies why we need `lockfile` even though it doesn't appear anywhere in `pip-audit`'s own code.~~
With this, all of the dependencies in #203 are accounted for on our side.
Closes #203.
=> setup: use CacheControl[filecache]

setup.py
The v1.0.0 release included a breaking schema change.
```
pip_audit/_format/cyclonedx.py:36: error: List comprehension has incompatible type List[str]; expected List[VulnerabilityAdvisory]
Found 1 error in 1 file (checked 50 source files)
make: *** [lint] Error 1
```
The new advisory type requires a URL (which we don't have) so it wasn't immediately obvious what to do about this. So I'm proposing to pin our version behind 1.0.0 while we figure this out.
=> setup: Pin CycloneDX behind the 1.0.0 release

.github/workflows/ci.yml, .github/workflows/docs.yml, CONTRIBUTING.md, Makefile
This removes the need for a `make dev` target. It also simplifies `CONTRIBUTING.md` to make `make` a requirement and remove documentation of the 'manual' steps, since these will probably quickly become out of date over time.
=> Simplify local development steps/guide

pip_audit/_cli.py, test/test_cli.py
Fixing a small nit. The test is kind of an experiment and thus a bit rough as it's not super easy to test this right now, ideally this will become cleaner in time.
=> Handle plurals correctly in output

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_format/columns.py, pip_audit/_format/cyclonedx.py, pip_audit/_format/interface.py, pip_audit/_format/json.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_cyclonedx.py, test/format/test_json.py, test/test_cli.py
=> _format: Show vulnerabilities removed via `--fix` in JSON and columnar formats

CHANGELOG.md, Makefile, README.md, pip_audit/_cli.py
~~WIP, needs testing.~~
Closes #220.
=> cli: support `--fix --dry-run`

pip_audit/_virtual_env.py
As part of a8f9fa2b9266f65cdf2efa33ca8c62903370765f, we stopped piping the package installation output and instead let it show up in stdout which messes with our CLI spinner. Let's pass in `subprocess.DEVNULL` again.
=> _virtual_env: Pipe installation output to /dev/null

pip_audit/_cli.py, pip_audit/_dependency_source/pip.py, pip_audit/_fix.py
I purposely didn't add anything to the `CHANGELOG` since `--fix` hasn't been included in a released version yet.
=> pip, _fix: Add missing CLI feedback

README.md, pip_audit/_cli.py, pip_audit/_dependency_source/requirement.py, pip_audit/_service/interface.py, pip_audit/_service/pypi.py, setup.py, test/dependency_source/test_requirement.py, test/service/test_pypi.py
=> requirement, pypi: Add a --require-hashes flag

Makefile
This makes it easier to perform local development after merging changes to dependencies. `setup.py` doesn't change frequently during routine development, so this shouldn't regularly incur any additional development-time overhead.
=> Makefile: predicate venv on setup.py

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/resolvelib/__init__.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/test_resolvelib.py
=> _cli, resolvelib: Support for custom indices

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_format/columns.py, pip_audit/_format/cyclonedx.py, pip_audit/_format/interface.py, pip_audit/_format/json.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_cyclonedx.py, test/format/test_json.py
=> _cli, _format: Print skipped packages even when no vulns are found

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_dependency_source/pip.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, setup.py, test/dependency_source/test_pip.py, test/dependency_source/test_resolvelib.py
WIP; needs https://github.com/di/pip-api/pull/131 to support requirements files and not just environments.
Closes #237.
=> pip_audit, test: allow editable packages to be skipped

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/pyproject.py, test/dependency_source/test_pyproject.py
=> Support `pyproject.toml`

CHANGELOG.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, setup.py, test/dependency_source/test_resolvelib.py
See: https://github.com/pypa/packaging/issues/527.
Fixes #248.
=> pip_audit/dependency_source: match candidate names against project

setup.py
Fixes the subdependency error that previously required us to pin `click`.
=> setup: pin black >= 22.3.0

.pre-commit-hooks.yaml, README.md
- Add a pip-audit pre-commit hook
- Use the `pass_filenames: false` so user has to specify args
- Add section with example usage to README.md
Test:
- Run with bandersnatch pre-commit pointed @ https://github.com/cooperlees/pip-audit
```shell
cooper-mbp:bandersnatch cooper$ ~/venvs/bs/bin/pre-commit run -a
[INFO] Initializing environment for git@github.com:cooperlees/pip-audit.git.
[INFO] Installing environment for git@github.com:cooperlees/pip-audit.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
...
pip-audit................................................................Passed
```
Fixes #252
=> Add Pre-Commit Hook

CHANGELOG.md, README.md, pip_audit/_cli.py
=> Add an `--output` option

CHANGELOG.md, pip_audit/_service/pypi.py
=> Canonicalize versions from PyPI API

CHANGELOG.md, pip_audit/_service/pypi.py, test/service/test_pypi.py
Fixes the fix in #263. This time, I'm going to add unit tests.
=> service/pypi: fix version parsing when enforcing hashes

.pre-commit-config.yaml
setuptools config was moved to pyproject.toml
=> ci(pre-commit): remove setup-cfg-fmt

Makefile, mypy.ini, pip_audit/_cache.py, pip_audit/_cli.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, pip_audit/_fix.py, pip_audit/_format/columns.py, pip_audit/_format/cyclonedx.py, pip_audit/_format/json.py, pip_audit/_service/interface.py, pip_audit/_state.py, pip_audit/_virtual_env.py, pyproject.toml
This ratchets down our typing some more, and moves our Mypy configuration into `pyproject.toml` (removing another top-level config file.)
Doing this also helped us catch a typing bug in `resolvelib`: https://github.com/sarugaku/resolvelib/issues/104
=> pip_audit: ratchet down typing

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_service/interface.py, test/service/test_interface.py, test/test_cli.py
This commit introduces a new flag to pip-audit's CLI (--ignore-vuln)
that takes a string representing a vulnerability id, if any of the
packages scanned detect said vulnerability, it will be ignored in the
final report.
This allows users of pip-audit to ignore certain vulnerabilities that
they may deem not exploitable for whatever reason.
The flag can be used multiple times to ignore multiple vulnerabilities.
Closes #245
=> cli: allow ignoring specific vulnerability IDs

CHANGELOG.md, pip_audit/_state.py
=> state: ensure that cursor is revealed when spinner exits

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_state.py, pyproject.toml
This simplifies the spinner implementation quite a bit, and brings us slightly closer in line with `pip`'s already vendored dependencies.
Closes #282.
=> cli, state: replace `progress` spinner with `rich.status`

CHANGELOG.md, pip_audit/_service/osv.py, test/service/test_osv.py
We shouldn't assume that any fields other than `id`
or `modified` exist, and we currently don't check the latter.
=> osv: fix incorrect schema assumptions

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_service/__init__.py, pip_audit/_service/interface.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, test/service/test_osv.py, test/service/test_pypi.py
These can occur if the user is behind a corporate firewall
or other network policy that blocks access to PyPI,
or in the unlikely event of a PyPI API outage.
See #286.
=> cli, service: better error handling for connection errors

CHANGELOG.md, pip_audit/_service/osv.py, test/service/test_osv.py
=> service/osv: guard against schema changes

CHANGELOG.md, pip_audit/_cache.py, test/test_cache.py
=> cache: respect pip's `PIP_NO_CACHE_DIR`

pyproject.toml
This fixes the lint in the CI and adds `toml` as a dependency.
We should do a release after this, since it's likely that `pyproject.toml` support was broken prior to this (outside of the development environment.)
=> pyproject: add missing toml deps

pyproject.toml
Follow-up to #292, now that CycloneDX has done a `2.5.1` release.
=> pyproject: relax cyclonedx version range

.github/workflows/ci.yml, CHANGELOG.md, Makefile, pip_audit/_cli.py
=> Respect `--cache-dir` and other flags when auditing project directories

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, pip_audit/_virtual_env.py, test/dependency_source/test_requirement.py
=> requirement, test: Correct `--fix` for subdependencies in requirements files

README.md
=> README: Documentation improvements

.github/workflows/release.yml, CONTRIBUTING.md, Makefile
This makes the release workflow slightly more manual, and aligns it with the workflow we use on `sigstore-python`.
Closes #302.
=> Refactor the release workflow

CHANGELOG.md, pip_audit/__init__.py
To get the `--format=markdown` changes out the door.
=> pip_audit: 2.4.0

CHANGELOG.md, pip_audit/_service/pypi.py, test/service/test_pypi.py
=> PyPI: Adjust JSON API use to handle upstream changes

.github/workflows/ci.yml, .github/workflows/release.yml
Since we've recently created a GitHub Action for `sigstore-python`, I figure we can use `pip-audit` as a testbed for it.
=> workflows: Sign releases with `sigstore-python`

pip_audit/_dependency_source/requirement.py, pyproject.toml, test/dependency_source/test_requirement.py
Extended discussion can be found at https://github.com/di/pip-api/issues/120. The `pip-requirements-parser` package is more complete and `pip-api` is not intending to support this API going forward (more detail in https://github.com/di/pip-api/issues/121) so we've decided to port `pip-audit` to `pip-requirements-parser` for the time being.
CC: @pombredanne
=> requirement: Parse requirements using `pip-requirements-parser` instead of `pip-api`

CHANGELOG.md, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, test/service/test_osv.py, test/service/test_pypi.py
The "details" field is frequently multiline and OSV allows it to be Markdown formatted, which causes problems for the surrounding columnar and Markdown formats. The correct field in our context is the "summary" field, which is specified as a short plaintext string.
Closes #314.
=> OSV, PyPI: Do not use "details" field for vuln summaries

CONTRIBUTING.md, Makefile
The ideas from #171 are good so I figure we should port them across to `pip-audit`.
=> Makefile: Tweak linting target and add new `reformat` target

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Skip requirements without an inferred name/specifier

pip_audit/_service/interface.py
No functional changes. This only serves to make API misuse slightly harder.
Closes #276.
=> service/interface: newtype vulnerability IDs

README.md, pip_audit/_cli.py
Some of these were incorrectly defaulted to plural forms, since their `dest=...`s are plural.
=> CLI: better meta-variables

.github/workflows/ci.yml, Makefile, pyproject.toml
This breaks the `dev` extra into two sub-extras, `test` and `lint`, allowing us to install only the subset of development dependencies needed for each. This in turn allows us to optimize our CI by installing only the dependencies required for each CI job.
Also: I'm using this PR to test `gitsign`, which is why the commits are marked as "Unverified". But they're signed via Sigstore + my GitHub identity!
=> pyproject: Use recursive extras to optimize the build process

.github/workflows/release.yml
This will attach the `.crt` and `.sig` files for each distribution file to the GitHub release.
=> workflows/release: bump sigstore action, upload signing artifacts to release

pyproject.toml
PR #337 introduced new classifiers, some of which cause the build to abort:
```
$ python -m flit build --format wheel
Fetching list of valid trove classifiers                                   I-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3 :: 3.10'     E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3 :: 3.7'      E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3 :: 3.8'      E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3 :: 3.9'      E-flit.validate
Config error: Invalid config values (see log)
```
Looking at [PyPI’s list of valid classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers) confirms that minor version classifiers have no intermediate `3` element.
I …
=> pyproject: fix classifiers

CHANGELOG.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, test/dependency_source/test_resolvelib.py
=> resolvelib: Consider a project "not found" if its PyPI project page has no links

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Remove incorrect assertion around URL requirements without egg fragment

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Improve error message for unpinned URL requirements

README.md
I have a pipenv project that I wanted to run pip-audit against. I found a simple workaround to convert the `Pipfile[.lock]` to a compatible `requirements.txt` file that pip-audit can process. I documented how I got this working in hopes it can help others with pipenv based projects. I've verified that the commands I added work properly, for both running locally and within GitHub CI.
Refs #85
=> Add details for running against pipenv projects

.github/workflows/scorecards.yml, README.md
This Pull Request intends to active the OpenSSF Scorecard, a tool to search for security risks through a series of automated checks.
Each automated task returns a score out of ten and a risk level, with remediation prompts to help you fix the problem. Besides, the badge shown in the readme file shows the score of the project.
I think it would be a very useful tool to improve the security of this project.
Any doubts or questions feel free to reach me out.
=> ✨ Enable OpenSSF Scorecard code scanning alert and badge

.github/workflows/release.yml
Now that we've reorg'd under the Sigstore org.
=> workflows/release: update gh-action-sigstore-python ref

CHANGELOG.md, pip_audit/_service/osv.py, test/service/test_osv.py
~~WIP; needs tests.~~
Closes #385. 
=> osv: skip results marked as "withdrawn"

pip_audit/_service/pypi.py, test/service/test_pypi.py
This will have no effect until pypi/warehouse#12443 is merged.
See #388.
=> service/pypi, test: add support for withdrawn vulnerabilities

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
This "fixes" #382 by:
~~1. Turning the unchecked exception into a controlled error~~
~~2. Fixing the error message (clarifying that `pip` doesn't support version pinning on URLs (VCS or otherwise), meaning that URL requirements cannot be used with `--no-deps` or `--require-hashes)~~
1. Explicitly skipping URL dependencies in `--no-deps` mode, which is compatible with how `pip --no-deps` behaves
Closes #382.
=> requirement: handle VCS URLs correctly in pinned mode

.github/workflows/release.yml
Using `@master` isn't officially supported, so this just moves us to the supported release ref.
=> workflows/release: use `gh-action-pypi-publish@release/v1`

pip_audit/_cli.py, pyproject.toml, test/test_cli.py
This doesn't give us full CLI coverage, but it gets us closer.
Spurred on by the bug in #399.
=> _cli, test: add test coverage for more CLI helpers

pip_audit/_service/osv.py
Per https://github.com/google/osv.dev/issues/810: this field really is optional, even though the API docs currently being served by osv.dev claim that it isn't.
=> service/osv: remove TODO

pip_audit/_dependency_source/resolvelib/pypi_provider.py
Looks like either mypy got smarter or resolvelib clarified its hints.
=> pypi_provider: remove an old lint ignore

CHANGELOG.md, README.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/resolvelib/test_pypi_provider.py, test/dependency_source/resolvelib/test_resolvelib.py
We now normalize all index URLs to end with a trailing slash, which PEP 503 encourages for maximum compatibility. This also has the added benefit of fixing a `urljoin` bug.
=> resolvelib: make PEP 503 handling more correct

pip_audit/_audit.py, pip_audit/_cache.py, pip_audit/_cli.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/pyproject.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, pip_audit/_fix.py, pip_audit/_format/columns.py, pip_audit/_format/cyclonedx.py, pip_audit/_format/interface.py, pip_audit/_format/json.py, pip_audit/_format/markdown.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, pip_audit/_state.py, pip_audit/_virtual_env.py, test/dependency_source/resolvelib/test_resolvelib.py, test/dependency_source/test_pip.py, test/dependency_source/test_pyproject.py, test/dependency_source/test_requirement.py, test/format/conftest.py, test/service/test_osv.py, test/service/test_pypi.py, test/test_fix.py
Prefer "intrinsic" hints and bar-style unions over `typing.*`
Closes #405.
=> pip_audit, test: modernize type hints

CHANGELOG.md, pip_audit/_service/interface.py, test/service/test_interface.py
=> service/interface: handle fractional seconds in RFC3339 timestamps

CHANGELOG.md, README.md, pip_audit/_cli.py
This also fixes a longstanding annoyance of mine in `pip-audit --help`, which was that `--output` showed its "default" as `None`.
Closes #431.
=> CLI: Don't create empty files on failure

pip_audit/_cli.py
I think #432 broke output when ~~there aren't any vulns~~ there are skips (in my case because I'm testing trunk) -- at least here, CI jobs are failing with e.g.:
```
format-audit: commands[1] /home/runner/work/jsonschema/jsonschema/.tox/format-audit/tmp> /home/runner/work/jsonschema/jsonschema/.tox/format-audit/bin/python -m pip_audit
No known vulnerabilities found
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/runner/work/jsonschema/jsonschema/.tox/format-audit/lib/python3.11/site-packages/pip_audit/__main__.py", line 8, in <module>
audit()
File "/home/runner/work/jsonschema/jsonschema/.tox/format-audit/lib/python3.11/site-packages/pip_audit/_cli.py", line 543, in audit …
```
=> CLI: write to the output file, not the Path object

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
We should cut a release to get #437 out the door.
=> treewide: prep 2.4.10

.flake8, CONTRIBUTING.md, Makefile, pip_audit/_audit.py, pip_audit/_cli.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/requirement.py, pip_audit/_format/columns.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, pip_audit/_virtual_env.py, pyproject.toml, test/dependency_source/test_pyproject.py, test/dependency_source/test_requirement.py
Similar to https://github.com/sigstore/sigstore-python/pull/353.
=> treewide: replace flake8 with ruff

CHANGELOG.md, pip_audit/_dependency_source/resolvelib/pypi_provider.py, test/dependency_source/resolvelib/test_resolvelib.py
We follow `pip`'s lead here and ignore these entirely, treating them as if they don't exist (while also warning the user).
Fixes #445.
See: https://github.com/pypa/packaging/issues/645
=> pip_audit, test: handle invalid requires-python specifiers

pip_audit/_format/columns.py, pip_audit/_format/markdown.py, pip_audit/_subprocess.py, test/dependency_source/resolvelib/test_resolvelib.py, test/dependency_source/test_pip.py, test/format/test_columns.py, test/format/test_markdown.py
`ruff` prefers this style, apparently.
=> pip_audit, test: `ruff` fixes

CHANGELOG.md, pip_audit/_virtual_env.py
This looks like an oversight on our part: we should keep setuptools upgraded along with `pip` and `wheel`, since the default environment one can be pretty old.
=> Include setuptools in upgrade set

pip_audit/_cache.py
I initially thought this was a false positive, but it looks like CPython's documentation on `IOError` is slightly stale.
xref https://github.com/charliermarsh/ruff/issues/1568
=> pip_audit: `ruff` fixes

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/resolvelib/test_resolvelib.py
~~WIP; just for visibility into where I've inserted debug statements.~~
Fixes #472.
=> Fix handling of prerelease-only resolutions

README.md
`pipenv` introduced a new `pipenv requirements` command that simplifies the process for generating a `requirements.txt` file, which can be piped directly into `pip-audit`
=> docs: update example of using pip-audit with pipenv

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/resolvelib.py, test/dependency_source/resolvelib/test_resolvelib.py, test/dependency_source/test_requirement.py
This has been broken since we moved away from `pip-api` to `pip-requirements-parser` for parsing. Unfortunately, unit tests didn't pick up on this since we were passing the `pip-api` object directly into the resolver.
=> requirement: Fix `--skip-editable` flag

Makefile, pyproject.toml
I've found this to be mildly annoying when running `make reformat`. Basically, `ruff` complains about lines being too long and I have to break lines manually to get past `ruff` and let `black` run.
`black` also needs to run after `ruff` since `ruff` could make edits that are incompatible with `black` so if we don't run `black` twice, we'd get into a situation where we'd need to run `make reformat` twice to make sure that there aren't any fixes needed.
=> pyproject.toml: Don't check for line-length with `ruff` since we're reformatting with `black`

CHANGELOG.md, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/requirement.py, pip_audit/_dependency_source/resolvelib/pypi_provider.py, test/dependency_source/resolvelib/test_pypi_provider.py
See #478: this isn't a full fix, but will hopefully improve the overall quality and debuggability of the errors produced.
=> Better errors when an invalid requirement is encountered

CHANGELOG.md, pip_audit/_subprocess.py, pip_audit/_virtual_env.py, test/test_virtual_env.py
This is just a followup to #523, with a few resiliency improvements:
* We collect the `pip` subprocess's `stderr` and display it with an error message on failure;
* We handle invalid UTF-8 more gracefully in both `stdout` and `stderr`, as there's no guarantee that `pip install ...` only prints valid unicode.
=> pip_audit: handle subprocess streams more cleanly

.pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
This preps 2.5.0 for release.
Minor version bump is technically not required, but commemorates/marks significant internal changes here (e.g. the refactoring to use `pip --report`).
=> Prep 2.5.0

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Close temporary files before passing them to `pip`

CHANGELOG.md, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement, test: Remove preresolved dependency optimization

CHANGELOG.md, pip_audit/_subprocess.py
=> _subprocess: perform invalid UTF-8 substitution

.github/workflows/release.yml
This runs the `release.yml` workflow in the `release` environment, which has been configured to require manual approval from a maintainer or admin of the repo.
=> workflows/release: configure environment

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_dependency_source/pyproject.py, pip_audit/_dependency_source/requirement.py, pip_audit/_virtual_env.py, test/dependency_source/test_requirement.py
Refactor index-url and extra-index-url options to not override config defined in 'pip.conf' unless explicitly specified via flags.
Closes #563
=> _dependency_source, _cli, test: Do not override `pip.conf` unless explicitly specified via flags

CHANGELOG.md, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> requirement: Check requirements using the canonical name when fixing

CHANGELOG.md, pyproject.toml
Looks like we were implicitly depending on this before, despite explicitly importing it, which is bad!
This adds a `2.29.*` constraint on our `requests` dep, which should block off a regression in `CacheControl` due to underlying changes in `urllib3` for the time being.
xrefs:
* https://github.com/psf/requests/issues/6437
* https://github.com/ionrock/cachecontrol/issues/292
=> pyproject: add, pin requests

CHANGELOG.md, pyproject.toml
~~**This should not be merged.**~~
~~This is just to evaluate the feasibility of a fork + determine whether anything else explodes.~~
See #616.
xrefs:
* https://github.com/psf/requests/issues/6437
* https://github.com/ionrock/cachecontrol/issues/292
=> pyproject: constrain urllib3

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_dependency_source/__init__.py, pip_audit/_dependency_source/interface.py, pip_audit/_dependency_source/requirement.py, test/dependency_source/test_requirement.py
=> Reintroduce dependency optimization

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/release.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, pyproject.toml
3.7 is EOL, and will soon begin dragging some of our support tooling.
=> bump minimum Python to 3.8

CHANGELOG.md, pip_audit/_virtual_env.py, pyproject.toml
=> _virtual_env: add --no-input to all invocations

pip_audit/_format/cyclonedx.py, pyproject.toml
get_instance() has been renamed to make_outputter() and removed in 6.0.0.
Fixes #705.
=> Allow build with cyclonedx-python-lib 6.0.0+

CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_format/columns.py, pip_audit/_format/json.py, pip_audit/_format/markdown.py, test/conftest.py, test/format/conftest.py, test/format/test_columns.py, test/format/test_json.py, test/format/test_markdown.py, test/test_cli.py
=> Add aliases to output.

CHANGELOG.md, pip_audit/_virtual_env.py, test/test_virtual_env.py
~~WIP, needs tests.~~
Closes https://github.com/pypa/pip-audit/issues/732
=> _virtual_env: handle PermissionError

CHANGELOG.md, README.md, pip_audit/_virtual_env.py
=> _virtual_env: allow pip to shell out to keyring

CHANGELOG.md, pip_audit/_dependency_source/pyproject.py, pip_audit/_dependency_source/requirement.py, test/conftest.py, test/dependency_source/test_requirement.py, test/test_cache.py, test/test_cli.py
While testings for others PRs, I get a lot of `permissionError`. Windows does not like moving/replacing files if there aren't properly closed or another process is still on it.
I also get normalization problems on paths used in tests, so I enforced a posix format instead of a basic string cast.
=> Many tests failing on Windows

CHANGELOG.md, README.md, pip_audit/_cli.py, pyproject.toml, test/test_cli.py
Adds a few environment variable getters that allow to override the default value of some CLI options.
Fixes #754
=> Allow environment variables to set CLI defaults

.github/workflows/release.yml
Removes two unnecessary dependencies and disables the caching settings (which have only a marginal effect since our build setup is tiny, but represents a cache poisoning risk).
Also deduplicates the `python-version` setting by having `setup-python` pull it from `pyproject.toml` instead.
=> workflows/release: cleanup

CHANGELOG.md, pip_audit/_cache.py, pyproject.toml, test/test_cache.py
A PR that aims to close #342.
All the logic is inside `_get_internal_cache_path` in `_cache.py`.
=> More respectful convention for caching

.github/workflows/zizmor.yml
This takes the run from ~2 mins for compiling
to a few seconds (for the online audits).
=> ci: zizmor: use uvx

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, pyproject.toml
https://github.com/econchick/interrogate/issues/164 was fixed!
Also removes bump, since aren't using it for releases at the moment.
=> pyproject: drop setuptools from lint dependencies

CHANGELOG.md, pip_audit/_cli.py, pip_audit/_subprocess.py
This eliminates two groups of resource leaks:
1. Our `Popen(...)` wrapper wasn't closing pipe FDs correctly, since it incorrectly assumed that pipe PDs were closed by default. This was fixed by using it as a context manager instead.
2. Our CLI used `argparse.FileType` for `-r, --requirements`, which always leaks a FD. It uses `Path` instead now.
Fixes #877 (CC @LeamHall to test, if possible!)
=> Remove two groups of resource leaks

.github/workflows/release.yml, .pre-commit-config.yaml, CHANGELOG.md, README.md, pip_audit/__init__.py
It's been a while since we've done a release and we've accumulated a few changes 🙂
=> chore: prep 2.8.0

.gitignore, CHANGELOG.md, README.md, pip_audit/_cli.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, test/test_cli.py
See https://github.com/pypa/pip-audit/issues/805 for more details.
Closes #805.
=> Adding --osv-url argument to allow use of private OSV vulnerability services

pip_audit/_service/esms.py, pip_audit/_service/interface.py, pip_audit/_service/osv.py, pip_audit/_service/pypi.py, test/service/test_interface.py
Depends on #903.
This takes `ids`, `description`, `fix_versions`, and `published` and
splits `ids` into `id` and aliases as appropriate internally. Priority
is given to PYSEC and CVE identifiers for `id`.
=> Implement helper to create `VulnerabilityResult`

pip_audit/_dependency_source/pylock.py, pip_audit/_dependency_source/pyproject.py, pyproject.toml, test/dependency_source/test_pyproject.py
If the pyproject.toml contain some new syntax ak the dictionnary inside a list, the actual toml lib used by pip audit fail to parse the line and raise `IndexError`
Example who not work with `toml` library.
```toml
commands = [["poetry", "run", "pytest", {replace = "posargs", default = [], extend=true}]]
```
Change with `tomli` and `tomli_w` for the dump part.
=> fix: use tomli to parse toml file, prevent decode error for new toml syntax
